AWSTemplateFormatVersion: '2010-09-09'

Transform:
- AWS::Serverless-2016-10-31

Resources:
  dataapisTaskLauncherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
